replicaCount: 1

image:
  repository: velvetaccardia/spring-helloworld
  pullPolicy: Always
  tag: ""
serviceAccount:
  create: true
  name: ""

service:
  type: NodePort
  port: 80
  name: hello-world
  targetPort: 8080
  enabled: false
containers:
  name: hello-world
