replicaCount: 1
image:
  repository: velvetaccardia/spring-helloworld
  pullPolicy: IfNotPresent
  tag: ""
service:
  type: NodePort
  port: 8080
  name: hello-world
  targetport: 8080
  enabled: false
containers:
  name: hello-world
