apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helloworld-spring.fullname" . }}
  labels:
    {{- include "helloworld-spring.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helloworld-spring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helloworld-spring.selectorLabels" . | nindent 8 }}
    spec:
      containers:
          name: {{ .Values.containers.name | quote }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
