apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-helloworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-helloworld
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-helloworld
    spec:
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: tcp
            containerPort: {{ .Values.service.targetPort }}
