name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-spring-app:latest

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag my-spring-app:latest ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest

    - name: Deploy Helm to EKS
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.4
      with:
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ env.AWS_REGION }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        name: ${{ env.HELM_RELEASE_NAME}}
        chart-path: ${{ env.HELM_CHART_PATH }}
